TODOLIST만들기(OOP) 만들기 리뷰 요청합니다.
code-squad/masteringjs_oop pull request #4
Opened 2018-09-28 13:29 UTC by hyeyoon

크롱님 :) 
TODOLIST 만들기 리뷰 요청합니다!

2018-09-30 11:00 UTC, nigayo commented
커밋로그 잘 쓰셨네요.
아주 조금만 더 구체적으로 작성하셔도 좋겠어요.

2018-09-30 11:12 UTC, crongro requested changes
잘 하셨습니다.

코드가 깔끔한 편이에요.

몇가지 리뷰남겨드립니다.  추가수정은 더 안하셔도 될 듯 하지만, 
일단 승인은 보류하겠습니다~ 
원하시면 수정을 나중에라도 해보세요~

2018-09-30 11:12 UTC, nigayo commented on todolist.js
> +const Todo = class {
클래스는 이렇게 보통 대문자로 시작해요.

2018-09-30 11:12 UTC, nigayo commented on todolist.js
> +    this.utils = new Utils();
클래스간에는 의존성을 줄이는 게 중요하다고 말씀드렸는데요.
지금코드에서는 
Utils클래스를 사용하고 싶으면, new Todo(new Utils()); 와 같이 Utils 객체를 생성해서 클래스 실행시 주입받는 게 의존성을 줄이는 방법입니다.
이렇게 되면 Todo 클래스는 Utils 클래스를 하드코딩해야 하는 부분은 없앨 수 있게 되죠.

2018-09-30 11:12 UTC, nigayo commented on todolist.js
> +    this.runCommand();
this.runCommand(this.order) 이렇게 전달할 수 있으면 좀더 좋아요

추가 설명하면, 
클래스를 쓰지만 그럼에도 불구하고, 함수에 인자로 전달해주면 this.xxx 으로 객체의 속성을 접근하는 코드가 줄게됩니다.
(나중에 테스트 할 때 좀 더 좋은 코드가 됩니다)

2018-09-30 11:12 UTC, nigayo commented on todolist.js
> +      	console.log('유효한 명령을 입력하세요.');
참고로, 
개발단계에서 에러를 발생하고 싶을때가 있으면 console.error 함수로 명확하게 에러를 발생하는 것도 좋아요~

2018-09-30 11:12 UTC, nigayo commented on todolist.js
> +    if (currentValue.status === status) {
조건문이 있다면, 
reduce 가 시작되기 전에, 
currentValue.status === status
이 부분을 filter함수로 한번 거리고, reduce하면 더 좋았을 거 같기도해요.

2018-09-30 11:12 UTC, nigayo commented on todolist.js
> +    this.statusList.forEach((status) => {
잘 하셨어요.
이부분도 filter & reduce조합으로 개선될 수 있어보여요~

2018-09-30 11:12 UTC, nigayo commented on todolist.js
> +const Utils = class {
유틸은 보통 객체리터럴로 표현하는데요.
지금 구현하신대로 클래스로 일관된 방식의 코딩도 좋아보이네요.

2018-10-01 14:28 UTC, hyeyoon commented on todolist.js
> +
어떻게 이 부분의 함수를 개선할 수 있는 방법을 고민하다가, 주석처리한 부분의 코드를 작성해보기도 했는데요. (this.defaultStatusCount = {todo: 0, doing: 0, done: 0};을 constructor에 설정을 한 후)

주석처리한 함수와 기존 함수를 reduce를 통해 구현한 함수 중 어떤 것이 더 효율적인 처리 방법일지 혹은 다른 방법으로 더 효율적인 방식으로 구현이 가능할지 궁금합니다.

2018-10-01 14:29 UTC, hyeyoon commented
리뷰해주신 것을 바탕으로 코드를 수정해봤습니다! 그리고 궁금한 점 코멘트 남겼습니다 :)

2018-10-02 07:26 UTC, crongro approved these changes
잘 수정하셨어요.

몇개 리뷰 남겼고요. reduce사용부분도 의견남겨드렸습니다~
수고하셨어요.

승인/머지 할게요.

2018-10-02 07:26 UTC, crongro commented on todolist.js
> +
먼저 이제 reduce에 대해서는 이제 잘 아실거 같네요. 
여러가지 방법이 있을텐데요.
먼저 가독성만 보면, 이렇게도 구현할 수 있겠네요
1) filter를 거쳐서 각 상태를 추출 
2) 1)의 결과를 count .
위 과정을 상태별로 반복.
성능에 크게 영향없고 괜찮은 코드 같습니다. (이미 구현한 방식이 비슷한거 같아요)

효율성을 우선으로, 전 이렇게 구현할 거 같긴해요. 
```javascript
const todoCountObj = this.todos.reduce( (o,task) => {
   const status = task.status;
   o[status]++;
   return o;
}, {"todo":0, "doing":0, "done":0});

console.log(`현재 갯수 상태 :  ${todoCountObj}`);

```

2018-10-02 07:26 UTC, crongro commented on todolist.js
>      this.statusList = ['todo', 'doing', 'done'];
지금 객체에서 속성이 많지 않지만, 더 줄일 수 있으면 그렇게 해보세요.
아니면 지역변수로 옮길 수 있으면 그렇게 하는게 좋고요.

2018-10-02 07:26 UTC, merged